---
# tasks file for install_docker
- name: Instalar pacotes necessários
  ansible.builtin.apt:
    update_cache: true
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Adicionar chave GPG oficial do Docker
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Adicionar repositório oficial do Docker
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Instalar docker
  ansible.builtin.apt:
    update_cache: true
    name:
      - docker-ce
      - docker-compose
    state: present

- name: Iniciar serviço Docker e habilitar na inicialização
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
